import { Box, VStack } from '@chakra-ui/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Header from '../Header/Header';
import HeaderActions from '../HeaderActions/HeaderActions';
import { HEADER_ACTIONS } from '../../context/SelectedActionContext';
import { findAction } from '../../utils/utils';

const Layout = ({ children }: any) => {
  const router = useRouter();
  const { slug } = router.query;
  const result = findAction(slug);

  return (
    <div>
      <Head>
        <title>Hat Signer Gate Portal</title>
        <meta
          content='Generated by @rainbow-me/create-rainbowkit'
          name='description'
        />
        <link href='/favicon.ico' rel='icon' />
      </Head>

      <VStack minH='100vh'>
        <Header />
        <Box alignSelf='flex-start'>
          <HeaderActions selectedAction={result as HEADER_ACTIONS} />
        </Box>
        {children}
      </VStack>
    </div>
  );
};

export default Layout;
