import { Box } from '@chakra-ui/layout';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import Content from '../components/Content/Content';
import Header from '../components/Header/Header';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content='Generated by @rainbow-me/create-rainbowkit'
          name='description'
        />
        <link href='/favicon.ico' rel='icon' />
      </Head>

      <main className={styles.main}>
        <Header />
        <Box className='py-8'>
          {/* TODO: Add a contiditon here to check if user has his wallet connected */}
          <Content />
        </Box>
      </main>

      <footer className={styles.footer}>
        <a href='https://rainbow.me' rel='noopener noreferrer' target='_blank'>
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
