import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header/Header';
import MainContent from '../components/MainContent/MainContent';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hat Signer Gate Portal</title>
        <meta
          content='Generated by @rainbow-me/create-rainbowkit'
          name='description'
        />
        <link href='/favicon.ico' rel='icon' />
      </Head>

      <main className={styles.main}>
        <Header />
        <MainContent />
      </main>
    </div>
  );
};

export default Home;
