import Head from 'next/head';
import Header from '../components/Header/Header';
import styles from '../styles/Home.module.css';

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Hat Signer Gate Portal</title>
        <meta
          content='Generated by @rainbow-me/create-rainbowkit'
          name='description'
        />
        <link href='/favicon.ico' rel='icon' />
      </Head>

      <main className={styles.main}>
        <Header />
        {children}
      </main>
    </div>
  );
};

export default Layout;
